### PR TITLE
Set specific launch UUID.

### PR DESCRIPTION
**Pull request by ArtPL**

### CODE REVIEW

**Comment by nvborisenko** [comment]
@ArtPL I don't see `uuid` in StartLaunchRequest

image

**Comment by ArtPL** [comment]
> @ArtPL I don't see `uuid` in StartLaunchRequest
> 
> image

https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md#start-launch
But it is in the documentation and it works

**Comment by nvborisenko** [comment]
@HardNorth what is functionality hidden by this property? Looks like something is mismatching.

**Comment by nvborisenko** [comment]
@ArtPL what benefit you get if you introduce this property?

**Comment by ArtPL** [comment]
We will use our system UDID of launch instead of saving ReportPortal UUID

**Comment by ArtPL** [comment]
@nvborisenko Do you have plans to merge this request?

**Comment by nvborisenko** [comment]
@reportportal/backend-contributors please comment whether this property is expected and should be displayed in swagger docs.

**Comment by Yumfriez** [comment]
We have this property. It's just hidden. So now it's possible to provide your UUID instead of auto-generated

**Comment by ArtPL** [comment]
Thanks for the merge.
When will you update the package in NuGet?

**Comment by nvborisenko** [comment]
Couple of days. Planning to include it into v3.0.5

**Pull request merged**
