### PR TITLE
Add snupkg to artifact

### PR DESCRIPTION
**Pull request by Aleh-Yanushkevich**

### CODE REVIEW

**Review by nvborisenko — APPROVED** [review]

**Comment by nvborisenko** [comment]
We can simplify it
```yaml
path: pkgs/*.[s]nupkg
```

**Comment by Aleh-Yanushkevich** [comment]
> We can simplify it
> 
> ```yaml
> path: pkgs/*.[s]nupkg
> ```

I've tried to use this pattern on online checkers and it failed. I'll try it for ci workflow initially, just to check.

**Comment by nvborisenko** [comment]
Checked this one `pkgs/*.?(s)nupkg` in tool, should work. Up to you use it or not, very likely your version is straightforward and clear.

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko only *.snpukg was found by this pattern:
image

I'll revert changes.

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko seems that not all glob patterns is supported in the action:
image

let's keep it as is.

**Pull request merged**
