### PR TITLE
Add existed README file to NuGet package.

### PR DESCRIPTION
**Pull request by Aleh-Yanushkevich**
Added existed README file to NuGet package for making it visible on [nuget.org](https://www.nuget.org/packages/ReportPortal.Client/).

### CODE REVIEW

**Comment by Aleh-Yanushkevich** [comment]
@nvborisenko could you please rerun it?
image

**Comment by nvborisenko** [comment]
Reran it, failed again. Seems API spec was changed, or bug on server side.

**Comment by Aleh-Yanushkevich** [comment]
Strange, because it works locally.

**Review by nvborisenko — APPROVED** [review]

**Comment by nvborisenko** [comment]
Sporadic issue, at least now tests are green.

**Comment by Aleh-Yanushkevich** [comment]
@Aleh-Yanushkevich got it, thanks!

**Pull request merged**
